// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable}  bg-[#020E1A]  antialiased`  }
//       >
//         <Navbar/>
//         {/* {children} */}
//         <main className="min-h-screen">
//           {children}
//         </main>
//         <Footer />
//       </body>
//     </html>
//   );
// }

import { Metadata } from "next";
import ClientLayout from "./ClientLayout";
import ClientProvider from "@/components/ClientProvide";
export const metadata: Metadata = {
  title: "The composer",
  description: "Your description here",
  keywords: "your, keywords, here",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (<>

    <html lang="en">
      <body>
        <ClientProvider>
          <ClientLayout>{children}</ClientLayout>
        </ClientProvider>
      </body>
    </html>
  </>)
}