import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Carousel } from "@/components/ui/carousel";
import { CarouselSize } from "@/components/ReviewSection";
// import { WhyChooseUs } from "@/components/WhyChooseUs";
import HeroSection from "@/components/HeroSection";
import CarouselSection from "@/components/CarouselSection";
import Head from 'next/head';
import { WhatPeopleSaySection } from "@/components/WhatPeopleSaySection";
import ContactForm from "@/components/ContactForm";
import HowWeWork from "@/components/HowDoWeWorkSection";
import HowDoWeWorkSection from "@/components/HowDoWeWorkSection";
import DevelopmentSection from "@/components/DevelopmentSection";
import DesignServices from "@/components/DesignServices";
import OurWorkSpeakSection from "@/components/OurWorkSpeakSection";
import WhyChooseUs from "@/components/WhyChooseUs";
import LetsTalk from "@/components/LetsTalk";

export default function Home() {
  return (
    //     <div className="grid grid-rows-[20px_1fr_20px] items-center justify-items-center min-h-screen p-8 pb-20 gap-16 sm:p-20 font-[family-name:var(--font-geist-sans)]">
    //       {/* <main className="flex flex-col gap-8 row-start-2 items-center sm:items-start"> */}
    //       {/* </main> */}
    //     </div>

    <>
      <Head>
        <title>Wizzom</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <main>
        <section >

          <HeroSection />
          <DevelopmentSection />
          <DesignServices />
          <WhatPeopleSaySection />
          <WhyChooseUs />
          <HowDoWeWorkSection />
          <OurWorkSpeakSection />
          <ContactForm />

        </section>
      </main>
    </>
  );
}
